#!/usr/bin/env node
/**
 * Walk `patches/<chassis>/**\/*.ncsxpatch.yaml`, regenerate:
 *
 *   patches/README.md              — chassis-level index (one row per chassis dir)
 *   patches/<chassis>/README.md    — patches in this chassis, grouped by module
 *
 * Idempotent: rerunning produces byte-identical output when nothing
 * has changed (so the CI commit is a no-op on no-op runs and doesn't
 * waste a workflow trigger).
 *
 * Invalid patches are surfaced as warnings but do NOT fail the build —
 * the PR validator (`scripts/validate.mjs`) is the gate. We don't want
 * a broken contribution to lock the index for the rest of the repo.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readPatch } from './lib/patch.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = dirname(__dirname);
const PATCHES_DIR = join(REPO_ROOT, 'patches');
const GENERATED_NOTE =
  '<!-- AUTO-GENERATED by scripts/build-indexes.mjs — edits will be overwritten. -->';

async function listDirs(root) {
  const entries = await readdir(root, { withFileTypes: true });
  return entries.filter((e) => e.isDirectory()).map((e) => e.name);
}

async function listPatchFiles(dir) {
  const out = [];
  async function walk(d) {
    const entries = await readdir(d, { withFileTypes: true });
    for (const e of entries) {
      const p = join(d, e.name);
      if (e.isDirectory()) {
        await walk(p);
      } else if (e.isFile() && e.name.endsWith('.ncsxpatch.yaml')) {
        out.push(p);
      }
    }
  }
  await walk(dir);
  return out.sort();
}

function escapeMd(text) {
  return text.replace(/\|/g, '\\|').replace(/\n+/g, ' ');
}

function firstLine(text) {
  return text.split('\n').find((l) => l.trim().length > 0) ?? '';
}

function sumEdits(patch) {
  return patch.modules.reduce((n, m) => n + Object.keys(m.edits).length, 0);
}

/** Build the per-chassis README. Returns the markdown string. */
function renderChassisReadme(chassisDirName, patches) {
  const lines = [];
  lines.push(GENERATED_NOTE);
  lines.push('');
  lines.push(`# ${chassisDirName} patches`);
  lines.push('');
  if (patches.length === 0) {
    lines.push('_No patches yet._');
    lines.push('');
    lines.push('See the [contributing guide](../../README.md#contributing) to add one.');
    return lines.join('\n') + '\n';
  }
  lines.push(`${patches.length} patch${patches.length === 1 ? '' : 'es'}.`);
  lines.push('');

  // Group by module list — a patch covering multiple modules appears under each.
  const byModule = new Map();
  for (const { file, patch } of patches) {
    for (const m of patch.modules) {
      const key = m.module.toUpperCase();
      if (!byModule.has(key)) byModule.set(key, []);
      byModule.get(key).push({ file, patch, modulePatch: m });
    }
  }
  const moduleNames = [...byModule.keys()].sort();

  for (const mod of moduleNames) {
    lines.push(`## ${mod}`);
    lines.push('');
    lines.push('| Patch | Description | Coding indexes | Author | Keywords |');
    lines.push('|---|---|---|---|---|');
    for (const { file, patch, modulePatch } of byModule.get(mod)) {
      const rel = relative(join(PATCHES_DIR, chassisDirName), file);
      const desc = escapeMd(
        modulePatch.description ?? firstLine(patch.description ?? '') ?? '',
      );
      const cis = modulePatch.coding_indexes?.length
        ? modulePatch.coding_indexes.map((c) => `\`${c}\``).join(', ')
        : '_any_';
      const author = patch.author ? escapeMd(patch.author) : '_anon_';
      const keywords = patch.keywords?.length
        ? patch.keywords.map((k) => `\`${k}\``).join(', ')
        : '—';
      lines.push(
        `| [${escapeMd(patch.title)}](${rel}) | ${desc || '—'} | ${cis} | ${author} | ${keywords} |`,
      );
    }
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

/** Build the chassis-list README at `patches/README.md`. */
function renderChassisIndex(rows) {
  const lines = [];
  lines.push(GENERATED_NOTE);
  lines.push('');
  lines.push('# Community patches');
  lines.push('');
  if (rows.length === 0) {
    lines.push('_No chassis folders yet._ See the');
    lines.push('[contributing guide](../README.md#contributing) to add the first patch.');
    return lines.join('\n') + '\n';
  }
  const totalPatches = rows.reduce((n, r) => n + r.patchCount, 0);
  const totalEdits = rows.reduce((n, r) => n + r.editCount, 0);
  lines.push(
    `Patches grouped by chassis. **${rows.length}** chassis · ` +
      `**${totalPatches}** patch${totalPatches === 1 ? '' : 'es'} · ` +
      `**${totalEdits}** FSW/PSW edit${totalEdits === 1 ? '' : 's'} total.`,
  );
  lines.push('');
  lines.push('| Chassis | Patches | Edits | Modules touched |');
  lines.push('|---|---|---|---|');
  for (const r of rows) {
    const mods = r.modules.length > 0 ? r.modules.map((m) => `\`${m}\``).join(', ') : '—';
    lines.push(
      `| [**${r.dir}**](${r.dir}/) | ${r.patchCount} | ${r.editCount} | ${mods} |`,
    );
  }
  lines.push('');
  return lines.join('\n') + '\n';
}

/** Compare new content to existing; only write if different. Returns true if written. */
async function writeIfChanged(path, content) {
  let existing = '';
  try {
    existing = await readFile(path, 'utf-8');
  } catch {
    // missing — treat as changed
  }
  if (existing === content) return false;
  await writeFile(path, content);
  return true;
}

async function main() {
  const chassisDirs = await listDirs(PATCHES_DIR);
  chassisDirs.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  const indexRows = [];
  let totalWritten = 0;

  for (const dir of chassisDirs) {
    const chassisPath = join(PATCHES_DIR, dir);
    const files = await listPatchFiles(chassisPath);
    const patches = [];
    const modulesSeen = new Set();
    let editCount = 0;
    for (const file of files) {
      try {
        const patch = await readPatch(file);
        patches.push({ file, patch });
        editCount += sumEdits(patch);
        for (const m of patch.modules) modulesSeen.add(m.module.toUpperCase());
      } catch (err) {
        console.warn(`[index] skipping — ${err.message}`);
      }
    }
    const md = renderChassisReadme(dir, patches);
    const wrote = await writeIfChanged(join(chassisPath, 'README.md'), md);
    if (wrote) totalWritten++;
    indexRows.push({
      dir,
      patchCount: patches.length,
      editCount,
      modules: [...modulesSeen].sort(),
    });
  }

  const indexMd = renderChassisIndex(indexRows);
  const wroteIndex = await writeIfChanged(join(PATCHES_DIR, 'README.md'), indexMd);
  if (wroteIndex) totalWritten++;

  console.log(
    `[index] ${chassisDirs.length} chassis · ` +
      `${indexRows.reduce((n, r) => n + r.patchCount, 0)} patches · ` +
      `${totalWritten} README${totalWritten === 1 ? '' : 's'} updated`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
